server:
 port: 7000
 error.include-message: always
 
spring:
 application.name: product-composite-service

# This configuration (below) will be replaced by a service discovery mechanism
app:
 product-service:
  host: localhost
  port: 7001
  
 recommendation-service:
  host: localhost
  port: 7002
  
 review-service:
  host: localhost
  port: 7003
