#spring.config.import: "configserver:"
spring.config.import: "configserver:http://${spring.cloud.config.username}:${spring.cloud.config.password}@config-server:8888"

spring:
 application.name: product-composite
 cloud.config:
  failFast: true
  retry:
   initial-interval: 3000
   multiplier: 1.3
   max-interval: 10000
   max-attempts: 3
  uri: http://localhost:8888
  username: ${CONFIG_SERVER_USR}
  password: ${CONFIG_SERVER_PWD}

#resilience4j.timelimiter:
# instances:
#  product:
#   timeoutDuration: 2s
#   
#management.health.circuitbreakers.enabled: true
#
#resilience4j.circuitbreaker:
# instances:
#  product:
#   allowHealthIndicatorToFail: false
#   registerHealthIndicator: true
#   slidingWindowType: COUNT_BASED
#   slidingWindowSize: 5
#   failureRateThreshold: 50
#   waitDurationInOpenState: 10000
#   permittedNumberOfCallsInHalfOpenState: 3
#   automaticTransitionFromOpenToHalfOpenEnabled: true
#   ignoreExceptions:
#    - com.david.microservices.alpha.api.exceptions.InvalidInputException
#    - com.david.microservices.alpha.api.exceptions.NotFoundException
#
#resilience4j.retry:
# instances:
#  product:
#   maxAttempts: 3
#   waitDuration: 3000
#   retryExceptions:
#    - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError

#management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
#management.tracing.sampling.probability: 1.0
#logging.pattern.level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

---
spring.config.activate-profile: docker

spring.cloud.config.uri: http://config-server:8888