#spring.config.import: "configserver:"
spring.config.import: "configserver:http://${spring.cloud.config.username}:${spring.cloud.config.password}@config-server:8888"

spring:
 application.name: review
 cloud.config:
  failFast: true
  retry:
   initial-interval: 3000
   multiplier: 1.3
   max-interval: 10000
   max-attempts: 3
  uri: http://localhost:8888
  username: ${CONFIG_SERVER_USR}
  password: ${CONFIG_SERVER_PWD}
   

---
spring.config.activate-profile: docker

spring.cloud.config.uri: http://config-server:8888